// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	Textb  string `json:"textb"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID    string   `json:"id"`
	Text  string   `json:"text"`
	Textb string   `json:"textb"`
	Arr   []string `json:"arr,omitempty"`
	Done  bool     `json:"done"`
	User  *User    `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
